"""empty message

Revision ID: 1878eb90a305
Revises: c5e10bf50c26
Create Date: 2026-05-25 15:44:35.794429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1878eb90a305'
down_revision = 'c5e10bf50c26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###
