"""empty message

Revision ID: 215aeb9e4570
Revises: 1b12b08659bc
Create Date: 2026-05-30 02:54:06.477529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '215aeb9e4570'
down_revision = '1b12b08659bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents_securite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adresse', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('ville', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents_securite', schema=None) as batch_op:
        batch_op.drop_column('ville')
        batch_op.drop_column('adresse')

    # ### end Alembic commands ###
