"""empty message

Revision ID: 28f81a092a32
Revises: 624a91b940dc
Create Date: 2026-04-27 13:08:05.276088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f81a092a32'
down_revision = '624a91b940dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents_securite', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('agents_securite_prestataire_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('agents_securite_tenant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key('fk_agents_prestataire_tenant', 'prestataires', ['tenant_id', 'prestataire_id'], ['tenant_id', 'id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('audit_log_tenant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('demandes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_demandes_numero_ticket'))
        batch_op.create_index(batch_op.f('ix_demandes_numero_ticket'), ['numero_ticket'], unique=False)
        batch_op.create_unique_constraint('uq_demandes_tenant_numero', ['tenant_id', 'numero_ticket'])
        batch_op.create_foreign_key('fk_demandes_site_tenant', 'sites', ['tenant_id', 'site_id'], ['tenant_id', 'id'])
        batch_op.create_foreign_key('fk_demandes_client_tenant', 'clients', ['tenant_id', 'client_id'], ['tenant_id', 'id'])

    with op.batch_alter_table('fichiers', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_fichiers_demande_tenant', 'demandes', ['tenant_id', 'demande_id'], ['tenant_id', 'id'])

    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_interactions_demande_tenant', 'demandes', ['tenant_id', 'demande_id'], ['tenant_id', 'id'])

    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_sites_client_tenant', 'clients', ['tenant_id', 'client_id'], ['tenant_id', 'id'])

    with op.batch_alter_table('telephony_events', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('telephony_events_tenant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key('fk_telephony_events_demande_tenant', 'demandes', ['tenant_id', 'demande_id'], ['tenant_id', 'id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telephony_events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('fk_telephony_events_demande_tenant', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('telephony_events_tenant_id_fkey'), 'tenants', ['tenant_id'], ['id'])
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sites_client_tenant', type_='foreignkey')

    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_interactions_demande_tenant', type_='foreignkey')

    with op.batch_alter_table('fichiers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_fichiers_demande_tenant', type_='foreignkey')

    with op.batch_alter_table('demandes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_demandes_client_tenant', type_='foreignkey')
        batch_op.drop_constraint('fk_demandes_site_tenant', type_='foreignkey')
        batch_op.drop_constraint('uq_demandes_tenant_numero', type_='unique')
        batch_op.drop_index(batch_op.f('ix_demandes_numero_ticket'))
        batch_op.create_index(batch_op.f('ix_demandes_numero_ticket'), ['numero_ticket'], unique=True)

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('audit_log_tenant_id_fkey'), 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('agents_securite', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('fk_agents_prestataire_tenant', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('agents_securite_tenant_id_fkey'), 'tenants', ['tenant_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('agents_securite_prestataire_id_fkey'), 'prestataires', ['prestataire_id'], ['id'])
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###
