"""add_jsonb_columns_demandes_commandes

Revision ID: 2e137f775942
Revises: 0e05af69b750
Create Date: 2026-06-18 13:55:30.194850

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2e137f775942'
down_revision = '0e05af69b750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demandes_commandes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('moyens_acces', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('equipements_site', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('risques_specifiques', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('besoins_agents', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demandes_commandes', schema=None) as batch_op:
        batch_op.drop_column('besoins_agents')
        batch_op.drop_column('risques_specifiques')
        batch_op.drop_column('equipements_site')
        batch_op.drop_column('moyens_acces')

    # ### end Alembic commands ###
