"""empty message

Revision ID: 3332c8a7359b
Revises: 215aeb9e4570
Create Date: 2026-05-30 02:55:02.218495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3332c8a7359b'
down_revision = '215aeb9e4570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents_securite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_agent', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents_securite', schema=None) as batch_op:
        batch_op.drop_column('type_agent')

    # ### end Alembic commands ###
