"""add_siret_type_site_adresse_intervention

Revision ID: 335b1d64956b
Revises: 43ae77b7e04d
Create Date: 2026-06-16 14:32:05.345460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '335b1d64956b'
down_revision = '43ae77b7e04d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('siret', sa.String(length=14), nullable=True))

    with op.batch_alter_table('demandes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adresse_intervention', sa.String(length=300), nullable=True))

    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_site', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_column('type_site')

    with op.batch_alter_table('demandes', schema=None) as batch_op:
        batch_op.drop_column('adresse_intervention')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('siret')

    # ### end Alembic commands ###
