"""empty message

Revision ID: 3555cc94ab87
Revises: 69722da39bf8
Create Date: 2026-04-27 13:47:15.171432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3555cc94ab87'
down_revision = '69722da39bf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demandes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('demandes_site_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('demandes_client_id_fkey'), type_='foreignkey')

    with op.batch_alter_table('fichiers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fichiers_demande_id_fkey'), type_='foreignkey')

    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('interactions_demande_id_fkey'), type_='foreignkey')

    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('sites_client_id_fkey'), type_='foreignkey')

    with op.batch_alter_table('telephony_events', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('telephony_events_demande_id_fkey'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telephony_events', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('telephony_events_demande_id_fkey'), 'demandes', ['demande_id'], ['id'])

    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('sites_client_id_fkey'), 'clients', ['client_id'], ['id'])

    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('interactions_demande_id_fkey'), 'demandes', ['demande_id'], ['id'])

    with op.batch_alter_table('fichiers', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fichiers_demande_id_fkey'), 'demandes', ['demande_id'], ['id'])

    with op.batch_alter_table('demandes', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('demandes_client_id_fkey'), 'clients', ['client_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('demandes_site_id_fkey'), 'sites', ['site_id'], ['id'])

    # ### end Alembic commands ###
