"""empty message

Revision ID: 43ae77b7e04d
Revises: 642691205c9c
Create Date: 2026-06-06 17:32:20.335829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43ae77b7e04d'
down_revision = '642691205c9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_contacts_tenant_id', ['tenant_id', 'id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_constraint('uq_contacts_tenant_id', type_='unique')

    # ### end Alembic commands ###
