"""empty message

Revision ID: 624a91b940dc
Revises: 42ffb0a11f43
Create Date: 2026-04-27 11:22:21.714767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '624a91b940dc'
down_revision = '42ffb0a11f43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('fonction', sa.String(length=100), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenants_code'), ['code'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('PERMANENCIER', 'MANAGER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('agent_login', sa.String(length=50), nullable=True),
    sa.Column('station_extension', sa.String(length=20), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=50), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='auditaction'), nullable=False),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_record_id'), ['record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_table_name'), ['table_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_user_id'), ['user_id'], unique=False)

    op.create_table('clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('code_client', sa.String(length=50), nullable=False),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('contact_principal', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code_client', name='uq_clients_tenant_code')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_code_client'), ['code_client'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('prestataires',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_prestataires_tenant_code')
    )
    with op.batch_alter_table('prestataires', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prestataires_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('tenant_users',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('membership_role', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'user_id')
    )
    op.create_table('token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('token_type', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_blocklist_jti'), ['jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_token_blocklist_user_id'), ['user_id'], unique=False)

    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('agent_login', sa.String(length=50), nullable=True),
    sa.Column('station_extension', sa.String(length=20), nullable=True),
    sa.Column('session_start', sa.DateTime(), nullable=False),
    sa.Column('session_end', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'ENDED', 'EXPIRED', 'REVOKED', name='sessionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('active_tenant_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['active_tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_active_tenant_id'), ['active_tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_jti'), ['jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('agents_securite',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('matricule', sa.String(length=50), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('qualification', sa.String(length=100), nullable=True),
    sa.Column('taux_horaire', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('prestataire_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['prestataire_id'], ['prestataires.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'matricule', name='uq_agents_tenant_matricule')
    )
    with op.batch_alter_table('agents_securite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_securite_matricule'), ['matricule'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_securite_prestataire_id'), ['prestataire_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_securite_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('contacts_clients',
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('est_principal', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('contact_id', 'client_id')
    )
    op.create_table('sites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('code_site', sa.String(length=50), nullable=False),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('responsable_site', sa.String(length=100), nullable=True),
    sa.Column('effectif_requis', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code_site', name='uq_sites_tenant_code')
    )
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sites_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sites_code_site'), ['code_site'], unique=False)
        batch_op.create_index(batch_op.f('ix_sites_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('contacts_sites',
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('est_principal', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('contact_id', 'site_id')
    )
    op.create_table('demandes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_ticket', sa.String(length=50), nullable=False),
    sa.Column('type_demande', sa.Enum('ANOMALIE', 'COMMANDE', 'PLANNING', 'ADMIN', name='typedemande'), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('permanencier_id', sa.Integer(), nullable=False),
    sa.Column('closed_by_id', sa.Integer(), nullable=True),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('statut', sa.Enum('NOUVELLE', 'EN_COURS', 'EN_ATTENTE', 'RESOLUE', 'CLOTUREE', 'ANNULEE', name='statutdemande'), nullable=False),
    sa.Column('priorite', sa.Enum('BASSE', 'NORMALE', 'HAUTE', 'URGENTE', name='prioriteniveau'), nullable=False),
    sa.Column('sla_deadline', sa.DateTime(), nullable=True),
    sa.Column('date_resolution', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['closed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['permanencier_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('demandes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_demandes_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_demandes_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_demandes_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_demandes_numero_ticket'), ['numero_ticket'], unique=True)
        batch_op.create_index(batch_op.f('ix_demandes_permanencier_id'), ['permanencier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_demandes_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_demandes_statut'), ['statut'], unique=False)
        batch_op.create_index(batch_op.f('ix_demandes_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_demandes_type_demande'), ['type_demande'], unique=False)

    op.create_table('demandes_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categorie', sa.String(length=100), nullable=True),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('date_echeance', sa.DateTime(), nullable=True),
    sa.Column('validation_requise', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['demandes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('demandes_anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nature_anomalie', sa.String(length=100), nullable=True),
    sa.Column('equipement_concerne', sa.String(length=200), nullable=True),
    sa.Column('localisation_precise', sa.String(length=200), nullable=True),
    sa.Column('impact_securite', sa.Boolean(), nullable=True),
    sa.Column('action_corrective', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['demandes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('demandes_commandes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_commande', sa.String(length=100), nullable=True),
    sa.Column('quantite', sa.Integer(), nullable=True),
    sa.Column('budget_estime', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fournisseur_suggere', sa.String(length=200), nullable=True),
    sa.Column('date_livraison_souhaitee', sa.DateTime(), nullable=True),
    sa.Column('bon_commande', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['demandes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('demandes_plannings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_modification', sa.String(length=100), nullable=True),
    sa.Column('agent_concerne_id', sa.Integer(), nullable=True),
    sa.Column('date_debut', sa.DateTime(), nullable=True),
    sa.Column('date_fin', sa.DateTime(), nullable=True),
    sa.Column('motif', sa.Text(), nullable=True),
    sa.Column('agent_remplacant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_concerne_id'], ['agents_securite.id'], ),
    sa.ForeignKeyConstraint(['agent_remplacant_id'], ['agents_securite.id'], ),
    sa.ForeignKeyConstraint(['id'], ['demandes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fichiers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('demande_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('nom_fichier', sa.String(length=255), nullable=False),
    sa.Column('chemin_fichier', sa.String(length=500), nullable=False),
    sa.Column('taille', sa.Integer(), nullable=True),
    sa.Column('type_mime', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['demande_id'], ['demandes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fichiers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fichiers_demande_id'), ['demande_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fichiers_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fichiers_uploaded_by_id'), ['uploaded_by_id'], unique=False)

    op.create_table('interactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('demande_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type_interaction', sa.Enum('APPEL', 'EMAIL', 'WHATSAPP', 'NOTE', 'CHANGEMENT_STATUT', name='typeinteraction'), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=True),
    sa.Column('ancien_statut', sa.String(length=50), nullable=True),
    sa.Column('nouveau_statut', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['demande_id'], ['demandes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interactions_demande_id'), ['demande_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interactions_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interactions_user_id'), ['user_id'], unique=False)

    op.create_table('telephony_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_session_id', sa.Integer(), nullable=False),
    sa.Column('demande_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Enum('CALL_START', 'CALL_END', 'CALL_TRANSFER', 'CALL_HOLD', name='eventtype'), nullable=False),
    sa.Column('caller_number', sa.String(length=20), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('call_uuid', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['demande_id'], ['demandes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_session_id'], ['user_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telephony_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telephony_events_demande_id'), ['demande_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telephony_events_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telephony_events_user_session_id'), ['user_session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telephony_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telephony_events_user_session_id'))
        batch_op.drop_index(batch_op.f('ix_telephony_events_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_telephony_events_demande_id'))

    op.drop_table('telephony_events')
    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_interactions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_interactions_demande_id'))

    op.drop_table('interactions')
    with op.batch_alter_table('fichiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fichiers_uploaded_by_id'))
        batch_op.drop_index(batch_op.f('ix_fichiers_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_fichiers_demande_id'))

    op.drop_table('fichiers')
    op.drop_table('demandes_plannings')
    op.drop_table('demandes_commandes')
    op.drop_table('demandes_anomalies')
    op.drop_table('demandes_admin')
    with op.batch_alter_table('demandes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_demandes_type_demande'))
        batch_op.drop_index(batch_op.f('ix_demandes_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_demandes_statut'))
        batch_op.drop_index(batch_op.f('ix_demandes_site_id'))
        batch_op.drop_index(batch_op.f('ix_demandes_permanencier_id'))
        batch_op.drop_index(batch_op.f('ix_demandes_numero_ticket'))
        batch_op.drop_index(batch_op.f('ix_demandes_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_demandes_contact_id'))
        batch_op.drop_index(batch_op.f('ix_demandes_client_id'))

    op.drop_table('demandes')
    op.drop_table('contacts_sites')
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sites_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_sites_code_site'))
        batch_op.drop_index(batch_op.f('ix_sites_client_id'))

    op.drop_table('sites')
    op.drop_table('contacts_clients')
    with op.batch_alter_table('agents_securite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_securite_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_agents_securite_prestataire_id'))
        batch_op.drop_index(batch_op.f('ix_agents_securite_matricule'))

    op.drop_table('agents_securite')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_jti'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_active_tenant_id'))

    op.drop_table('user_sessions')
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blocklist_user_id'))
        batch_op.drop_index(batch_op.f('ix_token_blocklist_jti'))

    op.drop_table('token_blocklist')
    op.drop_table('tenant_users')
    with op.batch_alter_table('prestataires', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prestataires_tenant_id'))

    op.drop_table('prestataires')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_clients_code_client'))

    op.drop_table('clients')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_table_name'))
        batch_op.drop_index(batch_op.f('ix_audit_log_record_id'))

    op.drop_table('audit_log')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_code'))

    op.drop_table('tenants')
    op.drop_table('contacts')
    # ### end Alembic commands ###
