"""empty message

Revision ID: 642691205c9c
Revises: ad6d9d78528c
Create Date: 2026-06-06 13:58:14.359475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '642691205c9c'
down_revision = 'ad6d9d78528c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('code_postal', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('contact_principal_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.NUMERIC(precision=10, scale=7), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.NUMERIC(precision=10, scale=7), nullable=True))
        batch_op.create_foreign_key(None, 'contacts', ['contact_principal_id'], ['id'])
        batch_op.drop_column('responsable_site')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsable_site', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('contact_principal_id')
        batch_op.drop_column('email')
        batch_op.drop_column('code_postal')
        batch_op.drop_column('logo_url')

    # ### end Alembic commands ###
