"""empty message

Revision ID: 6c0ba40f8b91
Revises: b4d50dfd96fd
Create Date: 2026-04-27 13:17:57.226630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c0ba40f8b91'
down_revision = 'b4d50dfd96fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_clients_tenant_id'), type_='unique')

    with op.batch_alter_table('demandes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_demandes_tenant_id'), type_='unique')

    with op.batch_alter_table('prestataires', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_prestataires_tenant_id'), type_='unique')

    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_sites_tenant_id'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_sites_tenant_id'), ['tenant_id', 'id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('prestataires', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_prestataires_tenant_id'), ['tenant_id', 'id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('demandes', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_demandes_tenant_id'), ['tenant_id', 'id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_clients_tenant_id'), ['tenant_id', 'id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
