"""add_siret_type_site_adresse_intervention

Revision ID: 850d79b2fd7c
Revises: 335b1d64956b
Create Date: 2026-06-16 14:32:16.383049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '850d79b2fd7c'
down_revision = '335b1d64956b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
