"""empty message

Revision ID: 89aa681d329d
Revises: f560c5e774fc
Create Date: 2026-06-05 12:35:52.551718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89aa681d329d'
down_revision = 'f560c5e774fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('adresse', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('ville', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('tenant_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('partner_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('agent_securite_id', sa.Integer(), nullable=True))
        batch_op.alter_column('telephone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_contacts_partner_id'), ['partner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_unique_constraint(None, ['agent_securite_id'])
        batch_op.create_foreign_key(None, 'prestataires', ['partner_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'agents_securite', ['agent_securite_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_contacts_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_contacts_partner_id'))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('telephone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('agent_securite_id')
        batch_op.drop_column('partner_id')
        batch_op.drop_column('tenant_id')
        batch_op.drop_column('type')
        batch_op.drop_column('ville')
        batch_op.drop_column('adresse')
        batch_op.drop_column('avatar_url')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('logo_url')

    # ### end Alembic commands ###
