"""add code_postal to agent_securite

Revision ID: a7fa67a8b0be
Revises: b1c2d3e4f5a6
Create Date: 2026-06-24 14:56:53.397530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7fa67a8b0be'
down_revision = 'b1c2d3e4f5a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents_securite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code_postal', sa.String(length=20), nullable=True))

    with op.batch_alter_table('demandes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_demandes_updated_by'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_demandes_created_by'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['updated_by_id'], ['id'])

    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emails_demande_id'), ['demande_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emails_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emails_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_preferences_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_preferences_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('smtp_settings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_smtp_settings_tenant'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_smtp_settings_tenant_id'))
        batch_op.create_index(batch_op.f('ix_smtp_settings_tenant_id'), ['tenant_id'], unique=True)

    with op.batch_alter_table('tenant_invitations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_tenant_invitations_token'), type_='unique')
        batch_op.create_index(batch_op.f('ix_tenant_invitations_token_hash'), ['token_hash'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_invitations_token_hash'))
        batch_op.create_unique_constraint(batch_op.f('uq_tenant_invitations_token'), ['token_hash'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('smtp_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_smtp_settings_tenant_id'))
        batch_op.create_index(batch_op.f('ix_smtp_settings_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_smtp_settings_tenant'), ['tenant_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_preferences_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_preferences_tenant_id'))

    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emails_user_id'))
        batch_op.drop_index(batch_op.f('ix_emails_message_id'))
        batch_op.drop_index(batch_op.f('ix_emails_demande_id'))

    with op.batch_alter_table('demandes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_demandes_created_by'), 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_demandes_updated_by'), 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('agents_securite', schema=None) as batch_op:
        batch_op.drop_column('code_postal')

    # ### end Alembic commands ###
