"""add code_postal to agent_securite

Revision ID: a7fa67a8b0be
Revises: b1c2d3e4f5a6
Create Date: 2026-06-24 14:56:53.397530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7fa67a8b0be'
down_revision = 'b1c2d3e4f5a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents_securite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code_postal', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents_securite', schema=None) as batch_op:
        batch_op.drop_column('code_postal')
    # ### end Alembic commands ###
