"""empty message

Revision ID: ad6d9d78528c
Revises: 89aa681d329d
Create Date: 2026-06-05 14:20:28.402046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad6d9d78528c'
down_revision = '89aa681d329d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ville', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('code_postal', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('code_postal')
        batch_op.drop_column('ville')

    # ### end Alembic commands ###
