"""empty message

Revision ID: b4356232fba2
Revises: 850d79b2fd7c
Create Date: 2026-06-16 15:15:00.542230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4356232fba2'
down_revision = '850d79b2fd7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
