"""equipement_concerne_string

Revision ID: b8565ce8f5a1
Revises: 2e137f775942
Create Date: 2026-06-18 14:13:52.968671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8565ce8f5a1'
down_revision = '2e137f775942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demandes_anomalies', schema=None) as batch_op:
        batch_op.alter_column('equipement_concerne',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demandes_anomalies', schema=None) as batch_op:
        batch_op.alter_column('equipement_concerne',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
