"""use_varchar_for_enums

Revision ID: c5e10bf50c26
Revises: e44416a83c37
Create Date: 2026-05-03 20:37:21.618605

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c5e10bf50c26'
down_revision = 'e44416a83c37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Suppression temporaire des clés étrangères pour permettre la modification de la contrainte unique
    op.drop_constraint('fk_fichiers_demande_tenant', 'fichiers', type_='foreignkey')
    op.drop_constraint('fk_interactions_demande_tenant', 'interactions', type_='foreignkey')
    op.drop_constraint('fk_telephony_events_demande_tenant', 'telephony_events', type_='foreignkey')

    with op.batch_alter_table('demandes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_discriminator', sa.String(length=50), nullable=False))
        batch_op.alter_column('type_demande',
               existing_type=postgresql.ENUM('ANOMALIE', 'COMMANDE', 'PLANNING', 'ADMIN', name='typedemande'),
               type_=sa.Enum('ANOMALIE', 'COMMANDE', 'PLANNING', 'ADMIN', name='type_demande_enum', native_enum=False),
               existing_nullable=False)
        batch_op.alter_column('statut',
               existing_type=postgresql.ENUM('NOUVELLE', 'EN_COURS', 'EN_ATTENTE', 'RESOLUE', 'CLOTUREE', 'ANNULEE', name='statutdemande'),
               type_=sa.Enum('NOUVELLE', 'EN_COURS', 'EN_ATTENTE', 'RESOLUE', 'CLOTUREE', 'ANNULEE', name='statut_demande_enum', native_enum=False),
               existing_nullable=False)
        batch_op.alter_column('priorite',
               existing_type=postgresql.ENUM('BASSE', 'NORMALE', 'HAUTE', 'URGENTE', name='prioriteniveau'),
               type_=sa.Enum('BASSE', 'NORMALE', 'HAUTE', 'URGENTE', name='priorite_demande_enum', native_enum=False),
               existing_nullable=False)
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_demandes_closed_by_id'), ['closed_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_demandes_type_discriminator'), ['type_discriminator'], unique=False)
        batch_op.drop_column('type')

    # Recréation des clés étrangères avec la contrainte unique mise à jour/supprimée
    op.create_foreign_key('fk_fichiers_demande_tenant', 'fichiers', 'demandes', ['tenant_id', 'demande_id'], ['tenant_id', 'id'])
    op.create_foreign_key('fk_interactions_demande_tenant', 'interactions', 'demandes', ['tenant_id', 'demande_id'], ['tenant_id', 'id'])
    op.create_foreign_key('fk_telephony_events_demande_tenant', 'telephony_events', 'demandes', ['tenant_id', 'demande_id'], ['tenant_id', 'id'], ondelete='SET NULL')

    with op.batch_alter_table('demandes_admin', schema=None) as batch_op:
        batch_op.alter_column('categorie',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('RESSOURCES_HUMAINES', 'COMPTABILITE', 'CONTRAT', 'POLITIQUE', 'AUTRE', name='categorie_admin_enum', native_enum=False),
               existing_nullable=True)
        batch_op.alter_column('document_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('CONTRAT', 'FACTURE', 'RAPPORT', 'DEMANDE_OFFICIELLE', 'APPROBATION', 'AUTRE', name='type_document_admin_enum', native_enum=False),
               existing_nullable=True)
        batch_op.alter_column('validation_requise',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('demandes_anomalies', schema=None) as batch_op:
        batch_op.alter_column('nature_anomalie',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('DEFAUT_MATERIEL', 'BUG_LOGICIEL', 'PROBLEME_RESEAU', 'ERREUR_CONFIGURATION', 'AUTRE', name='nature_anomalie_enum', native_enum=False),
               existing_nullable=True)
        batch_op.alter_column('equipement_concerne',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Enum('SERVEUR', 'ORDINATEUR', 'IMPRIMANTE', 'TELEPHONE', 'ROUTEUR', 'LOGICIEL', 'AUTRE', name='equipement_concerne_enum', native_enum=False),
               existing_nullable=True)
        batch_op.alter_column('localisation_precise',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('impact_securite',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('demandes_commandes', schema=None) as batch_op:
        batch_op.alter_column('type_commande',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('ACHAT', 'RENOUVELLEMENT', 'MAINTENANCE', 'LICENCE', 'CONSULTATION', 'AUTRE', name='type_commande_enum', native_enum=False),
               existing_nullable=True)
        batch_op.alter_column('budget_estime',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('demandes_plannings', schema=None) as batch_op:
        batch_op.alter_column('type_modification',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('ABSENCE', 'CONGE', 'FORMATION', 'REUNION', 'REMPLACEMENT', 'AUTRE', name='type_modification_planning_enum', native_enum=False),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_demandes_plannings_agent_concerne_id'), ['agent_concerne_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_demandes_plannings_agent_remplacant_id'), ['agent_remplacant_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('demandes_plannings_agent_remplacant_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('demandes_plannings_agent_concerne_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['agent_concerne_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['agent_remplacant_id'], ['id'])

    with op.batch_alter_table('fichiers', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Suppression temporaire des clés étrangères avant d'altérer la table demandes
    op.drop_constraint('fk_telephony_events_demande_tenant', 'telephony_events', type_='foreignkey')
    op.drop_constraint('fk_interactions_demande_tenant', 'interactions', type_='foreignkey')
    op.drop_constraint('fk_fichiers_demande_tenant', 'fichiers', type_='foreignkey')

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('fichiers', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('demandes_plannings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('demandes_plannings_agent_concerne_id_fkey'), 'agents_securite', ['agent_concerne_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('demandes_plannings_agent_remplacant_id_fkey'), 'agents_securite', ['agent_remplacant_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_demandes_plannings_agent_remplacant_id'))
        batch_op.drop_index(batch_op.f('ix_demandes_plannings_agent_concerne_id'))
        batch_op.alter_column('type_modification',
               existing_type=sa.Enum('ABSENCE', 'CONGE', 'FORMATION', 'REUNION', 'REMPLACEMENT', 'AUTRE', name='type_modification_planning_enum', native_enum=False),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('demandes_commandes', schema=None) as batch_op:
        batch_op.alter_column('budget_estime',
               existing_type=sa.String(length=50),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('type_commande',
               existing_type=sa.Enum('ACHAT', 'RENOUVELLEMENT', 'MAINTENANCE', 'LICENCE', 'CONSULTATION', 'AUTRE', name='type_commande_enum', native_enum=False),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('demandes_anomalies', schema=None) as batch_op:
        batch_op.alter_column('impact_securite',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('localisation_precise',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('equipement_concerne',
               existing_type=sa.Enum('SERVEUR', 'ORDINATEUR', 'IMPRIMANTE', 'TELEPHONE', 'ROUTEUR', 'LOGICIEL', 'AUTRE', name='equipement_concerne_enum', native_enum=False),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('nature_anomalie',
               existing_type=sa.Enum('DEFAUT_MATERIEL', 'BUG_LOGICIEL', 'PROBLEME_RESEAU', 'ERREUR_CONFIGURATION', 'AUTRE', name='nature_anomalie_enum', native_enum=False),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('demandes_admin', schema=None) as batch_op:
        batch_op.alter_column('validation_requise',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('document_type',
               existing_type=sa.Enum('CONTRAT', 'FACTURE', 'RAPPORT', 'DEMANDE_OFFICIELLE', 'APPROBATION', 'AUTRE', name='type_document_admin_enum', native_enum=False),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('categorie',
               existing_type=sa.Enum('RESSOURCES_HUMAINES', 'COMPTABILITE', 'CONTRAT', 'POLITIQUE', 'AUTRE', name='categorie_admin_enum', native_enum=False),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('demandes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_demandes_type_discriminator'))
        batch_op.drop_index(batch_op.f('ix_demandes_closed_by_id'))
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('priorite',
               existing_type=sa.Enum('BASSE', 'NORMALE', 'HAUTE', 'URGENTE', name='priorite_demande_enum', native_enum=False),
               type_=postgresql.ENUM('BASSE', 'NORMALE', 'HAUTE', 'URGENTE', name='prioriteniveau'),
               existing_nullable=False)
        batch_op.alter_column('statut',
               existing_type=sa.Enum('NOUVELLE', 'EN_COURS', 'EN_ATTENTE', 'RESOLUE', 'CLOTUREE', 'ANNULEE', name='statut_demande_enum', native_enum=False),
               type_=postgresql.ENUM('NOUVELLE', 'EN_COURS', 'EN_ATTENTE', 'RESOLUE', 'CLOTUREE', 'ANNULEE', name='statutdemande'),
               existing_nullable=False)
        batch_op.alter_column('type_demande',
               existing_type=sa.Enum('ANOMALIE', 'COMMANDE', 'PLANNING', 'ADMIN', name='type_demande_enum', native_enum=False),
               type_=postgresql.ENUM('ANOMALIE', 'COMMANDE', 'PLANNING', 'ADMIN', name='typedemande'),
               existing_nullable=False)
        batch_op.drop_column('type_discriminator')

    # Recréation des clés étrangères d'origine
    op.create_foreign_key('fk_fichiers_demande_tenant', 'fichiers', 'demandes', ['tenant_id', 'demande_id'], ['tenant_id', 'id'])
    op.create_foreign_key('fk_interactions_demande_tenant', 'interactions', 'demandes', ['tenant_id', 'demande_id'], ['tenant_id', 'id'])
    op.create_foreign_key('fk_telephony_events_demande_tenant', 'telephony_events', 'demandes', ['tenant_id', 'demande_id'], ['tenant_id', 'id'], ondelete='SET NULL')

    # ### end Alembic commands ###
