"""replace_type_commande_enum_security_missions

Revision ID: c782f962779a
Revises: b4356232fba2
Create Date: 2026-06-18 13:49:17.442130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c782f962779a'
down_revision = 'b4356232fba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demandes_commandes', schema=None) as batch_op:
        batch_op.alter_column('type_commande',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.Enum('GARDIENNAGE', 'SURVEILLANCE_MOBILE', 'RONDES', 'INTERVENTION', 'FILTRAGE', 'PROTECTION_RAPPROCHEE', 'ACCUEIL_SECURITE', 'AUTRE', name='type_commande_enum', native_enum=False),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demandes_commandes', schema=None) as batch_op:
        batch_op.alter_column('type_commande',
               existing_type=sa.Enum('GARDIENNAGE', 'SURVEILLANCE_MOBILE', 'RONDES', 'INTERVENTION', 'FILTRAGE', 'PROTECTION_RAPPROCHEE', 'ACCUEIL_SECURITE', 'AUTRE', name='type_commande_enum', native_enum=False),
               type_=sa.VARCHAR(length=14),
               existing_nullable=True)

    # ### end Alembic commands ###
