"""empty message

Revision ID: e5b6200a46fd
Revises: 3555cc94ab87
Create Date: 2026-04-27 14:05:53.116435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5b6200a46fd'
down_revision = '3555cc94ab87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_users', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
