"""add_agent_concerne_to_demandes_anomalies

Revision ID: f25dc29abb83
Revises: b8565ce8f5a1
Create Date: 2026-06-18 16:56:41.238530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f25dc29abb83'
down_revision = 'b8565ce8f5a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demandes_anomalies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent_concerne_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_demandes_anomalies_agent_concerne_id'), ['agent_concerne_id'], unique=False)
        batch_op.create_foreign_key(None, 'agents_securite', ['agent_concerne_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demandes_anomalies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_demandes_anomalies_agent_concerne_id'))
        batch_op.drop_column('agent_concerne_id')

    # ### end Alembic commands ###
