"""empty message

Revision ID: f560c5e774fc
Revises: 3332c8a7359b
Create Date: 2026-05-30 02:57:08.175968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f560c5e774fc'
down_revision = '3332c8a7359b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents_securite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motorise', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents_securite', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('motorise')

    # ### end Alembic commands ###
